# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username if you have one
patreon: # Replace with your Patreon username if you have one
open_collective: # Replace with your Open Collective username if you have one
ko_fi: https://ko-fi.com/kadenschutt
tidelift: # Replace with your Tidelift username if you have one
community_bridge: # Replace with your Community Bridge username if you have one
liberapay: # Replace with your Liberapay username if you have one
issuehunt: # Replace with your IssueHunt username if you have one
otechie: # Replace with your Otechie username if you have one
lfx_crowdfunding: # Replace with your LFX Crowdfunding username if you have one
custom: ['https://buymeacoffee.com/kadenschutt']
